{
 "title": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 v3.0 - Security and Performance",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 v3.0 - Security and Performance",
 "tags": [
  "Veeam",
  "Office 365"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "vboserver",
    "label": "VBO Server",
    "query": "SHOW TAG VALUES FROM win_cpu WITH KEY=host"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"win_disk\" WITH KEY = \"instance\" WHERE host =~ /$vboserver/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "content": "![Veeam Backup for Microsoft Office 365 - Dashboard](https://upload.wikimedia.org/wikipedia/commons/7/74/Office_365_logo.png)\n\n\n\n"
  },
  {
   "title": "Total MB Restored - VEX",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT \"bytesrestored\" FROM \"veeam_office365_audit_vex\" WHERE (\"bytesrestored\"  != '') ",
     "select": [
      [
       { "params": [ "bytesrestored" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VEX # Executed times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "select": [
      [
       { "params": [ "operator" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VEO # Executed times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_audit_vone",
     "select": [
      [
       { "params": [ "operator" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VES # Executed times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_audit_vspo",
     "select": [
      [
       { "params": [ "operator" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RESTAPI # Keys Issued",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_audit_rest",
     "select": [
      [
       { "params": [ "restkey" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RESTAPI # Completed Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_audit_rest",
     "select": [
      [
       { "params": [ "restaction" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Server Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$vboserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - outlook.office365.com",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"ping\" WHERE (\"url\" = 'outlook.office365.com') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "outlook.office365.com" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage in %" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Privileged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$vboserver$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "RAM Usage in bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pool non-paged Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pool paged Bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$vboserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$vboserver$/ AND \"instance\" =~ /^$disk$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "Net Usage in bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes received" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmxnet3 Ethernet Adapter" }
     ]
    }
   ]
  },
  {
   "title": "Latency to Microsoft Office 365",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "Latency in ms" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "outlook.office365.com" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$vboserver$/" }
     ]
    }
   ]
  },
  { "title": "Security Logs - Last 25", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Microsoft Exchange Online Items Restored",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"exchangeobject\" AS \"Item Restored\" FROM \"veeam_office365_audit_vex\" WHERE (\"exchangeobject\"  != '') limit 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Restore from",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\",  \"restorefrom\" AS \"Restored From:\" FROM \"veeam_office365_audit_vex\" WHERE (\"restorefrom\" != '') limit 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Restore To",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"restoreto\" AS \"Restored To:\" FROM \"veeam_office365_audit_vex\" WHERE (\"restoreto\" != '')  limit 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Microsoft OneDrive for Business Items Restored",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Item to Restore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"message\" AS \"Item restored\" FROM \"veeam_office365_audit_vone\" WHERE \"message\" =~ /Item restore completed:*/  limit 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Microsoft SharePoint Online Items Restored",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "Item to Restore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"message\" AS \"Item restored\" FROM \"veeam_office365_audit_vspo\" WHERE \"message\" =~ /Full URL:*/  limit 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Item to Restore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"message\" AS \"IsOriginalLocation\" FROM \"veeam_office365_audit_vspo\" WHERE \"message\" =~ /IsOriginalLocation:*/  limit 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Item to Restore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"message\" AS \"IsRestoreToCloud \" FROM \"veeam_office365_audit_vspo\" WHERE \"message\" =~ /IsRestoreToCloud: */  limit 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Veeam Backup for Microsoft Office 365 RESTFul API Keys issued",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "Item to Restore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"restkey\" AS \"RESTAPI Key\" FROM \"veeam_office365_audit_rest\" WHERE  (\"restkey\"  != '') LIMIT 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Veeam Backup for Microsoft Office 365 RESTFul API Completed Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "alias": "Item to Restore",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_audit_vex",
     "query": "SELECT (\"timestamp\") AS \"Timestamp\", \"restaction\" AS \"RESTAPI Action\" FROM \"veeam_office365_audit_rest\" WHERE  (\"restaction\"  != '') LIMIT 25",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}